name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '18 1 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    # Run ESLint
    - name: Run ESLint
      uses: stefanoeb/eslint-action@1.0.0
    
    # Public to NPM registry
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: archcry/knkv-ical-filter-proxy
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
